template:
    templates:
        - {"templateId":"1","templateFilePath":"C:\\Code\\do\\2020\\202011\\kafka-study\\src\\main\\resources\\template\\template.json","active": true}
        - {"templateId":"2","templateFilePath":"C:\\Code\\do\\2020\\202011\\kafka-study\\src\\main\\resources\\template\\template.json","active": false}
    template-result-type: 0  # 0-文件获取 1-数据库获取 2-ES
    template-result-file-path: "C:\\Code\\do\\2020\\202011\\kafka-study\\src\\main\\resources\\template\\templateResult.json"

wechat:
    kafka:
        bootstrap_servers: "152.136.159.147:9092"
        acks_config: "all"
        partitioner_class: "com.imooc.jiangzh.kafka.producer.SamplePartition"